name: final_project_chicago_evictions

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pandas
  - numpy
  - geopandas
  - matplotlib
  - shapely
  - pyogrio
  - streamlit
  - plotly
  - altair
  - pip
  - pip:
      - vl-convert-python